sudo pacman -S --needed --noconfirm - <./arch-official-packages.txt

mv ./exclude-config.sh ./config.sh
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

sudo cp -r ./tmux.conf $HOME/.tmux.conf

# ==========================================
# Ask user if using Window Manager (default: Yes)
# ==========================================

read -p "Are you using a window manager? [Y/n]: " answer
answer=${answer:-Y}    # default = Yes

if [[ "$answer" =~ ^[Yy]$ ]]; then
    echo "Using Window Manager → inserting tmux.wm.conf"
    # Sisipkan ke paling atas file
    cat tmux.wm.conf "$HOME/.tmux.conf" > "$HOME/.tmux.conf.tmp" \
        && mv "$HOME/.tmux.conf.tmp" "$HOME/.tmux.conf"
else
    echo "NOT using WM → inserting tmux.nowm.conf"
    cat tmux.nowm.conf "$HOME/.tmux.conf" > "$HOME/.tmux.conf.tmp" \
        && mv "$HOME/.tmux.conf.tmp" "$HOME/.tmux.conf"
fi


sed -i '1i # WARNING: Edit tmux.conf file in ftr-tmux then run install.sh to override this file' ~/.bashrc
sed -i '1i # WARNING: This file is automatically generated. Do not edit manually.' ~/.bashrc


echo "To reload config inside tmux, ctrl+h+: and run -> source-file ~/.tmux.conf"
